- name: checking nginx installation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  - name: Start and enable nginx   
    ansible.builtin.service: 
     name: nginx
     state: started
     enabled: yes
  - name: Stop nginx
    ansible.builtin.service:
     name: nginx
     state: stopped
  - name: delete nginx
    ansible.builtin.package:
     name: nginx
     state: absent      


